/* This file is automatically generated with util/structgen */
typedef struct effect_b_index_data {
	int index;
} effect_b_index_data;
typedef struct effect_ph_item_data {
	int x;
	int y;
	int z;
	int weight;
	struct entity_s *parent;
	parent_ref_type parent_type;
} effect_ph_item_data;
typedef struct effect_tracer_data {
	int x;
	int y;
	int z;
	int cur_x;
	int cur_y;
	int cur_z;
	int speed;
} effect_tracer_data;
typedef struct effect_block_move_data {
	int x;
	int y;
	int z;
	int delay;
} effect_block_move_data;
typedef struct effect_stair_move_data {
	int dir;
	int delay;
} effect_stair_move_data;
typedef struct effect_render_data {
	uint8_t chr;
	uint8_t r;
	uint8_t g;
	uint8_t b;
	uint8_t a;
} effect_render_data;
typedef struct effect_limb_slot_data {
	struct entity_s *item;
} effect_limb_slot_data;
typedef struct effect_limb_hand_data {
	int grab_type;
	struct entity_s *item;
} effect_limb_hand_data;
typedef struct effect_punch_data {
	struct entity_s *ent;
	int delay;
} effect_punch_data;
typedef struct effect_material_data {
	material_type type;
	int dur;
} effect_material_data;
typedef struct effect_size_scale_data {
	int scale;
} effect_size_scale_data;
typedef struct effect_aim_data {
	int x;
	int y;
	int z;
	struct entity_s *ent;
} effect_aim_data;
typedef struct effect_attack_data {
	struct entity_s *ent;
	int type;
	int delay;
	struct entity_s *tool;
} effect_attack_data;
typedef struct effect_table_item_data {
	struct entity_s *item;
} effect_table_item_data;
typedef struct effect_s_punch_data {
	struct entity_s *ent;
} effect_s_punch_data;
typedef struct effect_s_bump_data {
	struct entity_s *ent;
	int force;
} effect_s_bump_data;
typedef struct effect_s_dmg_data {
	enum damage_type type;
	int val;
} effect_s_dmg_data;
typedef struct effect_rotation_data {
	rotation_type type;
	int rotation;
} effect_rotation_data;
typedef struct effect_a_pressure_plate_data {
	int thresold;
} effect_a_pressure_plate_data;
typedef struct effect_stats_data {
	int str;
	int dex;
	int spd;
} effect_stats_data;
typedef struct effect_ph_liquid_data {
	int amount;
	enum liquid_type type;
} effect_ph_liquid_data;
typedef struct effect_container_data {
	unsigned cont_mask;
	int capacity;
} effect_container_data;
typedef struct effect_container_item_data {
	struct entity_s *item;
} effect_container_item_data;
typedef struct effect_wet_data {
	enum liquid_type type;
	int amount;
} effect_wet_data;
