/* This file is automatically generated with util/structgen */
typedef struct effect_b_index_data {
	int index;
} effect_b_index_data;
typedef struct effect_ph_item_data {
	int x;
	int y;
	int z;
	int weight;
	struct entity_s *parent;
	parent_ref_type parent_type;
} effect_ph_item_data;
typedef struct effect_tracer_data {
	int x;
	int y;
	int z;
	int cur_x;
	int cur_y;
	int cur_z;
	int speed;
} effect_tracer_data;
typedef struct effect_block_move_data {
	int x;
	int y;
	int z;
	int delay;
} effect_block_move_data;
typedef struct effect_stair_move_data {
	int dir;
	int delay;
} effect_stair_move_data;
typedef struct effect_render_data {
	char chr;
	uint8_t r;
	uint8_t g;
	uint8_t b;
	uint8_t a;
} effect_render_data;
typedef struct effect_limb_slot_data {
	struct entity_s *item;
	uint32_t tag;
} effect_limb_slot_data;
typedef struct effect_limb_hand_data {
	int grab_type;
	struct entity_s *item;
} effect_limb_hand_data;
typedef struct effect_material_data {
	material_type type;
	int dur;
} effect_material_data;
typedef struct effect_aim_data {
	int x;
	int y;
	int z;
	struct entity_s *ent;
} effect_aim_data;
typedef struct effect_attack_data {
	struct entity_s *ent;
	enum attack_type type;
	int delay;
	struct entity_s *tool;
} effect_attack_data;
typedef struct effect_table_item_data {
	struct entity_s *item;
} effect_table_item_data;
typedef struct effect_s_bump_data {
	struct entity_s *ent;
	int force;
} effect_s_bump_data;
typedef struct effect_s_dmg_data {
	enum damage_type type;
	int val;
} effect_s_dmg_data;
typedef struct effect_rotation_data {
	rotation_type type;
	int rotation;
} effect_rotation_data;
typedef struct effect_a_pressure_plate_data {
	int thresold;
} effect_a_pressure_plate_data;
typedef struct effect_m_grab_data {
	int eff_tag;
	struct entity_s *ent;
} effect_m_grab_data;
typedef struct effect_m_drop_data {
	int eff_tag;
} effect_m_drop_data;
typedef struct effect_m_put_data {
	int eff_tag;
	struct entity_s *where;
} effect_m_put_data;
typedef struct effect_m_throw_data {
	int eff_tag;
	int x;
	int y;
	int z;
	int speed;
} effect_m_throw_data;
typedef struct effect_m_aim_for_data {
	int eff_tag;
	int x;
	int y;
	int z;
	struct entity_s *ent;
} effect_m_aim_for_data;
typedef struct effect_m_touch_data {
	int eff_tag;
	struct entity_s *ent;
} effect_m_touch_data;
typedef struct effect_stats_data {
	int str;
	int dex;
	int spd;
} effect_stats_data;
typedef struct effect_ph_liquid_data {
	int amount;
	enum liquid_type type;
} effect_ph_liquid_data;
typedef struct effect_container_data {
	unsigned cont_mask;
	int capacity;
} effect_container_data;
typedef struct effect_container_item_data {
	struct entity_s *item;
} effect_container_item_data;
typedef struct effect_wet_data {
	enum liquid_type type;
	int amount;
} effect_wet_data;
typedef enum effect_type {
	EF_B_NONEXISTENT,
	EF_B_INDEX,
	EF_PH_BLOCK,
	EF_PH_ITEM,
	EF_FALLING,
	EF_TRACER,
	EF_BLOCK_MOVE,
	EF_STAIR_MOVE,
	EF_RENDER,
	EF_NOPHYSICS,
	EF_LIMB_SLOT,
	EF_LIMB_HAND,
	EF_LIMB_LEG,
	EF_MATERIAL,
	EF_AIM,
	EF_ATTACK,
	EF_TABLE,
	EF_TABLE_ITEM,
	EF_FIRE,
	EF_S_TOUCH,
	EF_S_BUMP,
	EF_S_DMG,
	EF_ROTATION,
	EF_A_PRESSURE_PLATE,
	EF_A_CIRCLE_MOVE,
	EF_M_GRAB,
	EF_M_DROP,
	EF_M_PUT,
	EF_M_THROW,
	EF_M_AIM_FOR,
	EF_M_TOUCH,
	EF_R_TOUCH_RNG_TP,
	EF_R_TOUCH_TOGGLE_BLOCK,
	EF_R_TOUCH_SHOOT_PROJECTILE,
	EF_STATS,
	EF_PH_LIQUID,
	EF_CONTAINER,
	EF_CONTAINER_ITEM,
	EF_WET,
	EF_UNKNOWN = -1
} effect_type;
